---
title: "Single Regression Analysis with pairs of two Variables"
author: "Blind"
runtime: shiny
output: html_document
---
  
  <!-- Preparing Data -->
```{r loading_main_script, echo=FALSE, results='hide',message=FALSE, warning=FALSE, cache=FALSE}
if (Sys.info()['sysname'] == "Darwin") {
  setwd("~/Tresors/interaction-effects/R")
} else {
  setwd("/home/paul/R/interaction-effects/R")
}

source("load_spine.R")
source("regression_matrix.R")

library(ggplot2)
library(shiny)
library(ggvis)
```
Minimum of the regression matrix: `r min(goodness_of_fit_matrix, na.rm= TRUE)`.
Maximum of the regression matrix: `r max(goodness_of_fit_matrix, na.rm= TRUE)`.
```{r echo=FALSE,message=FALSE, warning=FALSE, error=FALSE, out.extra=FALSE}

# inputPanel(
#   sliderInput("minimum", "Minimum Heatmap:", min = -100, max = 100, value = min(goodness_of_fit_matrix, na.rm= TRUE)),
#   sliderInput("maximum", "Maximum Heatmap:", min = 0, max = 20, value = ceiling(max(goodness_of_fit_matrix, na.rm= TRUE)))
# )
inputPanel(
  sliderInput("minimum", "Minimum Heatmap:", min = -10, max = 20, value = 0),
  sliderInput("maximum", "Maximum Heatmap:", min = -10, max = 20, value = 1),
  selectInput("dependent", "Dependent Variable:", c(names(frame), "none"), selected = "none")
)

renderPlot({
  if (Sys.info()['sysname'] == "Darwin") {
    setwd("~/Tresors/interaction-effects/R")
  } else {
    setwd("/home/paul/R/interaction-effects/R")
  }
  if (input$dependent == "none")
    fit_matrix <- goodness_of_fit_matrix
  else
    fit_matrix <- create_goodness_of_fit_matrix_dependent(frame, dependent = input$dependent)
  qplot(x=Var1, y=Var2, data=reshape2::melt(fit_matrix), fill=value, geom="tile", xlab="dependent", ylab="independent") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_fill_gradient(limits=c(input$minimum, input$maximum), low = "white", high = "steelblue")
}, height = 1000, width = 1000)

```
